name: ssdc_companion_ui
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  uuid: ^3.0.7
  path_provider: ^2.0.15
  material_design_icons_flutter: ^7.0.7296
  path: ^1.8.3
  flutter_secure_storage: ^8.0.0
  flutter_i18n: ^0.33.0
  process_run: ^0.13.0
  http: ^0.13.6
  collection: ^1.17.1
  url_launcher: ^6.1.12
  archive: ^3.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/i18n/
    