name: ssdc_companion_api
description: A bridge between A1111s Stable Diffusion WebUI API and the SSDC app.
version: 1.0.0

environment:
  sdk: ^3.0.5

# Add regular dependencies here.
dependencies:
  archive: ^3.3.7
  async_zip: ^0.1.0
  crypt: ^4.3.0
  darq: ^2.0.0
  dotenv: ^4.1.0
  freezed_annotation: ^2.2.0
  http: ^1.1.0
  isar: ^3.1.0+1
  json_annotation: ^4.8.1
  shelf: ^1.4.1
  shelf_router: ^1.1.4

dev_dependencies:
  build_runner: ^2.4.5
  freezed: ^2.3.5
  isar_generator: ^3.1.0+1
  json_serializable: ^6.7.0
  lints: ^2.0.0
  test: ^1.21.0

  very_good_analysis: ^5.0.0+1
